#!/bin/bash

set -o pipefail
set -o errexit

BAZEL_PATH=/usr/bin

function usage() {
  local exitval=${1-1}
  cat >&2 << USAGE
usage:
  $0 <options>
    --verbose                     Emit verbose info. Default: false
USAGE
  # shellcheck disable=SC2086
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --verbose)
      set -o xtrace
      shift
      ;;
    -h | --help) usage 0 ;;
    *) usage ;;
  esac
done

function install_bazelisk() {
  go install github.com/bazelbuild/bazelisk@v1.26.0
  local -r BAZELISK="$(go env GOPATH)"/bin/bazelisk
  if [[ -n ${BAZEL_PATH} ]] && [[ -d ${BAZEL_PATH} ]]; then
    ln -s "${BAZELISK}" "${BAZEL_PATH}"/bazel
  fi
  # install the specified version of bazel
  local -r -x USE_BAZEL_VERSION="$(cat /scripts/.bazelversion)"
  "${BAZELISK}" version
  rm -rf /bazel_root/*
}

function install_crane() {
   go install github.com/google/go-containerregistry/cmd/crane@v0.20.3
   local -r CRANE="$(go env GOPATH)"/bin/crane
   ln -s "${CRANE}" /usr/bin/crane
}

install_bazelisk
install_crane
